title: 'first trial '
description: ' just for testing'
publishedDate: 2025-05-21T00:00:00.0000000
modifiedDate: 2025-05-21T00:00:00.0000000
tags:
- trail
- dotnet
categories:
- development
- education
customSlug: awwal-tajriba
